/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_laundry;

/**
 *
 * @author WINDOWS10
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class halaman_utama extends javax.swing.JFrame {

    /**
     * Creates new form halaman_utama
     */
    private String role;
    public void setLevel(String a){
        role=a;
        if(role.equals("admin")){
            
    } else if(role.equals("kasir")){
            crud.hide();
            crud_peng.hide();
    }else if(role.equals("owner")){
        registrasi_pelanggan.hide();
        crud.hide();  
        transaksi.hide();
    }
    else{
    JOptionPane.showMessageDialog(null,"Role tidak ditemukan");
    }
    }
    public halaman_utama() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registrasi_pelanggan = new javax.swing.JButton();
        crud = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        crud_peng = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(255, 0, 51));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/exit.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 230, 60));

        transaksi.setBackground(new java.awt.Color(255, 255, 153));
        transaksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/cash-flow.png"))); // NOI18N
        transaksi.setText("Transaksi");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 230, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Menu");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, -1, 855));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/Premium Vector _ Laundry time with new washing machine.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 642, 569));

        registrasi_pelanggan.setBackground(new java.awt.Color(255, 255, 153));
        registrasi_pelanggan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrasi_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/group.png"))); // NOI18N
        registrasi_pelanggan.setText("Registrasi Pelanggan");
        registrasi_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrasi_pelangganActionPerformed(evt);
            }
        });
        jPanel1.add(registrasi_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 63));

        crud.setBackground(new java.awt.Color(255, 255, 153));
        crud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/clean-clothes.png"))); // NOI18N
        crud.setText("Data Produk");
        crud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudActionPerformed(evt);
            }
        });
        jPanel1.add(crud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 230, 63));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Data Pengguna");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 181, 63));

        crud_peng.setBackground(new java.awt.Color(255, 255, 153));
        crud_peng.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crud_peng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/a.png"))); // NOI18N
        crud_peng.setText("Data Pengguna");
        crud_peng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crud_pengActionPerformed(evt);
            }
        });
        jPanel1.add(crud_peng, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, 63));

        jLabel3.setBackground(new java.awt.Color(51, 204, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/Frame Sky Light Backdrop Background.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 870));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/children's church vinyl wall svg - Bing.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 620, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void registrasi_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrasi_pelangganActionPerformed
        // TODO add your handling code here:
        registrasi a=new registrasi();
        a.show();
    }//GEN-LAST:event_registrasi_pelangganActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
        trans a=new trans();
        a.show();
    }//GEN-LAST:event_transaksiActionPerformed

    private void crud_pengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crud_pengActionPerformed
        // TODO add your handling code here:
        pengguna a=new pengguna();
        a.show();
        
    }//GEN-LAST:event_crud_pengActionPerformed

    private void crudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudActionPerformed
        // TODO add your handling code here:
        produk_paket a=new produk_paket();
        a.show();
    }//GEN-LAST:event_crudActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login a=new login();
        a.show();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crud;
    private javax.swing.JButton crud_peng;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JButton logout;
    private javax.swing.JButton registrasi_pelanggan;
    private javax.swing.JButton transaksi;
    // End of variables declaration//GEN-END:variables
}
