/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_laundry;

/**
 *
 * @author WINDOWS10
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
public class trans extends javax.swing.JFrame {

    /**
     * Creates new form trans
     */
    Connection con;
    DefaultTableModel tm;
    public void connect(){
       con=null;
       try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_laundry","root","");
                   } catch (Exception e){
                       System.out.print("EROR KUERI DATABASE:\n"+e+"\n\n");
                   }
       }
    private void id_otomatis(){
        try{
            Connection c = con;
            Statement s = c.createStatement();
            String sql ="SELECT *FROM tb_detail_transaksi ORDER BY id_detail DESC";
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String No = r.getString("id_detail");
                String otomatis =""+(Integer.parseInt(No)+1);
                txtiddetail.setText(otomatis);
        }else{
                txtiddetail.setText("1");
            }
            r.close();
            s.close();
        }catch (Exception e){
                System.out.println("autonumber error");
            }
    }
    private void id_trans(){
        try{
            Connection c = con;
            Statement s = c.createStatement();
            String sql ="SELECT *FROM tb_transaksi ORDER BY id_transaksi DESC";
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String No = r.getString("id_transaksi");
                String otomatis =""+(Integer.parseInt(No)+1);
                txtidtrans.setText(otomatis);
        }else{
                txtidtrans.setText("1");
            }
            r.close();
            s.close();
        }catch (Exception e){
                System.out.println("autonumber error");
            }
    }
    private void refreshTablePaket(){
    tm= new DefaultTableModel (null,
    new Object[]{"Id Paket","Jenis","Nama Paket","Harga"});
    tbl1.setModel(tm);
    tm.getDataVector().removeAllElements();
try{
    PreparedStatement s=con.prepareStatement("SELECT*FROM tb_paket");
    ResultSet r=s.executeQuery();
    while(r.next()){
        Object[]data={
            r.getString(1),
            r.getString(2),
            r.getString(3),
            r.getString(4)
           
};tm.addRow(data);
        }
}catch (Exception e){
    System.out.print("ERROR KUERI KE DATABASE\n"+e+"\n\n");
}
    }
  
    
    
    
    
    public void cbidmem(){
        try{
            PreparedStatement s = con.prepareStatement("SELECT * FROM tb_member");
            ResultSet r =s.executeQuery();
            while (r.next()){
                cbidmem.addItem(r.getString("id_member"));
            }
        }catch (SQLException e){
    }
    }
   
    public void cbiduser(){
        try{
            PreparedStatement s = con.prepareStatement("SELECT * FROM tb_user");
            ResultSet r =s.executeQuery();
            while (r.next()){
                cbidusr.addItem(r.getString("id_user"));
            }
        }catch (SQLException e){
    }
    }
    
    public void cbiddetail(){
        try{
            PreparedStatement s = con.prepareStatement("SELECT * FROM tb_detail_transaksi where dibayar ='belum dibayar'");
            ResultSet r =s.executeQuery();
            while (r.next()){
                cbiddtl.addItem(r.getString("id_detail"));
            }
        }catch (SQLException e){
    }
    }
    
    
    public trans() {
        initComponents();
        connect();
        refreshTablePaket();
        cbidmem();
        id_otomatis();
        id_trans();
        cbiduser();
        cbiddetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        caripaket = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtqty = new javax.swing.JTextField();
        txtnmpkt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbidmem = new javax.swing.JComboBox<>();
        tgl = new com.toedter.calendar.JDateChooser();
        btsw = new com.toedter.calendar.JDateChooser();
        tglbyr = new com.toedter.calendar.JDateChooser();
        cbidusr = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbsts = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txtkembali = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtiddetail = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtidtrans = new javax.swing.JTextField();
        lbltotal = new javax.swing.JTextField();
        cbiddtl = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblbyr = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setText("ORDER");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("PEMBAYARAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/Frame Sky Light Backdrop Background.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/Frame Sky Light Backdrop Background.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 560, 60));

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 490, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PAKET CUCIAN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("QTY");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Cari");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        jPanel1.add(caripaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 260, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));
        jPanel1.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 310, 30));
        jPanel1.add(txtnmpkt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 310, 30));

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Detail", "Nama Paket", "Qty", "Harga", "Total", "Id Paket", "Id Member", "Tanggal", "Batas Waktu", "Status"
            }
        ));
        jScrollPane2.setViewportView(tbl2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 590, 190));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 130, 40));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/delete.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 140, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/Frame Sky Light Backdrop Background.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 650, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/Frame Sky Light Backdrop Background.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 560, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Id Detail");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Total");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Id Member");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, 30));

        jPanel1.add(cbidmem, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 240, -1));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 180, -1));
        jPanel1.add(btsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 180, -1));
        jPanel1.add(tglbyr, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 240, -1));

        jPanel1.add(cbidusr, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 810, 120, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/floppy-disk.png"))); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 880, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/exit.png"))); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 880, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Nama Paket");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Tanggal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Batas Waktu");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Status");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        cbsts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "baru", "proses", "selesai", "diambil" }));
        jPanel1.add(cbsts, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 240, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Tanggal Bayar");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, -1, -1));

        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 700, 240, -1));
        jPanel1.add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 750, 240, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Bayar");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 700, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Kembalian");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 750, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Id User");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 810, -1, -1));

        txtiddetail.setEnabled(false);
        jPanel1.add(txtiddetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 220, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Id Detail");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_laundry/floppy-disk.png"))); // NOI18N
        jButton9.setText("ORDER");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Id Transaksi");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        txtidtrans.setEnabled(false);
        jPanel1.add(txtidtrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, 260, -1));
        jPanel1.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, 240, -1));

        jPanel1.add(cbiddtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 130, -1));

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 660, -1, -1));

        tblbyr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Paket", "Qty", "Total"
            }
        ));
        jScrollPane3.setViewportView(tblbyr);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 540, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          // TODO add your handling code here:
        String Tampilan="yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(Tampilan);
        String tanggal=String.valueOf(fm.format(tgl.getDate()));
        String btswaktu=String.valueOf(fm.format(btsw.getDate()));
        int i= tbl1.getSelectedRow();
        String harga=(String) tm.getValueAt(i,3);
        int Total=Integer.parseInt(harga);
        int qty=Integer.parseInt(txtqty.getText());
        int hasil=Total*qty;
        DefaultTableModel model=(DefaultTableModel) tbl2.getModel();
        model.addRow(new Object[]{
            txtiddetail.getText(),txtnmpkt.getText(),txtqty.getText(),harga,hasil,tbl1.getValueAt(i,0),cbidmem.getSelectedItem(),tanggal,btswaktu,cbsts.getSelectedItem()
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        // TODO add your handling code here:
        int kembali,bayar,total;
        total=Integer.parseInt(lbltotal.getText());
        bayar=Integer.parseInt(txtbayar.getText());
        kembali=bayar-total;
        txtkembali.setText(String.valueOf(kembali));
        
    }//GEN-LAST:event_txtbayarKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tm = new DefaultTableModel (null,
            new Object[] {"Id Paket","Jenis","Nama Paket","Harga"});
        tbl1.setModel(tm);
        tm.getDataVector().removeAllElements();
        try
        {
            PreparedStatement s=con.prepareStatement("SELECT * from tb_paket where nama_paket LIKE '%"+caripaket.getText().toString()+"%'");
            ResultSet r=s.executeQuery();
            while(r.next())
            {
                Object[]data={
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4)};
                tm.addRow(data);
            }
        }
        catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        // TODO add your handling code here:
        int i=tbl1.getSelectedRow();
        if(i==-1){
            return;
        }
        String nmpkt= (String)tm.getValueAt (i,2);
        txtnmpkt.setText(nmpkt);
    }//GEN-LAST:event_tbl1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String Tampilan="yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(Tampilan);
        String tanggal=String.valueOf(fm.format(tgl.getDate()));
        String btswaktu=String.valueOf(fm.format(btsw.getDate()));
        String dibayar ="belum dibayar";
        try{
            Connection c = con;
            int baris = tbl2.getRowCount();
            for (int a = 0; a < baris;a++){
                id_otomatis();
                PreparedStatement ps =con.prepareStatement("INSERT INTO tb_detail_transaksi VALUES (?,?,?,?,?,?,?,?,?)");
                ps.setString(1, txtiddetail.getText());
                ps.setString(2, tbl2.getValueAt (a,5).toString());
                ps.setString(3, tbl2.getValueAt (a,2).toString());
                ps.setString(4, cbidmem.getSelectedItem().toString());
                ps.setString(5, tanggal);
                ps.setString(6, btswaktu);
                ps.setString(7, cbsts.getSelectedItem().toString());
                ps.setString(8, dibayar);
                ps.setString(9, tbl2.getValueAt (a,4).toString());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data telah tersimpan");
            }
        }catch(Exception e){
            System.out.print("ERROR KUERI ke Database:\n"+e+"\n\n");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tblbyr.getModel();
        try{
            PreparedStatement s = con.prepareStatement("SELECT nama_paket, qty, total FROM tb_paket, tb_detail_transaksi WHERE "
                    + "tb_paket.id_paket=tb_detail_transaksi.id_paket AND id_detail LIKE '%" + cbiddtl.getSelectedItem().toString() + 
                    "%' AND tb_detail_transaksi.dibayar='belum dibayar'");
            ResultSet r = s.executeQuery();
            while (r.next()){
                Object[] data ={
                    r.getString(1),
                    r.getString(2),
                    r.getString(3)
                };
                model.addRow(data);
                int jumlah = model.getRowCount();
                int sum=0;
                for (int i = 0; i < jumlah; i++) {
                    int total = Integer.valueOf(model.getValueAt(i, 2).toString());
                    sum += total;
                }
                lbltotal.setText(String.valueOf(sum));
            }
        } catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String Tampilan="yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(Tampilan);
        String tgalbyr=String.valueOf(fm.format(tglbyr.getDate()));
        try{
            Connection c= con;
            int baris = tblbyr.getRowCount();
            for ( int a = 0; a < baris; a++ ){
                id_otomatis();
                PreparedStatement ps = con.prepareStatement ("INSERT INTO tb_transaksi VALUES (?,?,?,?)");
                ps.setString(1, txtidtrans.getText());
                ps.setString(2, cbiddtl.getSelectedItem().toString());
                ps.setString(3, tgalbyr);
                ps.setString(4, cbidusr.getSelectedItem().toString());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data telah tersimpan");
            }
        }catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n"+e+"\n\n");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel    model = (DefaultTableModel)tbl2.getModel();
        int row=tbl2.getSelectedRow();
        model.removeRow (row);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser btsw;
    private javax.swing.JTextField caripaket;
    private javax.swing.JComboBox<String> cbiddtl;
    private javax.swing.JComboBox<String> cbidmem;
    private javax.swing.JComboBox<String> cbidusr;
    private javax.swing.JComboBox<String> cbsts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lbltotal;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTable tblbyr;
    private com.toedter.calendar.JDateChooser tgl;
    private com.toedter.calendar.JDateChooser tglbyr;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtiddetail;
    private javax.swing.JTextField txtidtrans;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtnmpkt;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
